### PR TITLE
add MySQL as storage backend

### PR DESCRIPTION
**Pull request by smeinecke**
- split storage.py into storageSqlite.py and storage.py
- added storageMySQL class to use MySQL as backend
- updated SafeBrowsingList class to set storage backend by parameter

### CODE REVIEW

**Comment by afilipovich** [comment]
Hi Stefan,
thank you for contributing the code!

For now I have merged it to separate branch "multi_storage" as I want to make several changes before releasing it to public, in particular:
- unify DB config options
- add support for Postgres
- add provisions for automated testing

**Comment by smeinecke** [comment]
Sounds great!
I probably have to implement the old GSB protocol since yandex still only support gsb 2.3 .
Is this also a thing you would like to add?

**Comment by afilipovich** [comment]
Currently I do not plan to add support for Yandex API. In fact, since it is based on a different protocol, it makes sense to keep it as a separate library.

**Comment by nitmir** [comment]
Having mysql support would be very nice as it allow concurrent access to the database (for example, from multiples applications)

**Comment by asieira** [comment]
+1 to SQLAlchemy support for multiple database back-ends, that would be really interesting.

**Comment by afilipovich** [comment]
@asieira: the previous version of gglsbl had SQLAlchemy support, however I am hesitant to port it to the latest version. The main reason is performance. Using any DB but Sqlite on RAM FS is order of magnitude slower. Adding SQLAlchemy on top of it slows it down yet more.

So the overhead of using SQLAlchemy + any DB backend is really significant, e.g. hash prefix update currently takes several minutes on reasonably fast hardware. On SQLAlachemy + Postgres would take 0.5-2h depending on amount of changes.

Older version of protocol had different workflow which required fewer queries per update (but was more fragile and had fewer blacklists).

**Pull request closed without merging**
